version: "3.8"

services:
  mongo:
    image: mongo:5.0
    container_name: provinces_locations_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: provinces_locations_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - pl-network

  mongo_express:
    image: mongo-express:latest
    container_name: provinces_locations_mongo_express
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://admin:pass@mongo:27017/provinces_locations_db?authSource=admin"
      ME_CONFIG_BASICAUTH_ENABLE: "false"
    ports:
      - "8081:8081"
    networks:
      - pl-network

  microservice_provinces_get:
    image: keylet30/province-locations-wedding:provinces-get
    container_name: microservice_provinces_get
    env_file: .env
    depends_on:
      - mongo
    ports:
      - "4004:4004"
    networks:
      - pl-network

  microservice_provinces_delete:
    image: keylet30/province-locations-wedding:provinces-delete
    container_name: microservice_provinces_delete
    env_file: .env
    depends_on:
      - mongo
    ports:
      - "4005:4005"
    networks:
      - pl-network

  microservice_locations_get:
    image: keylet30/province-locations-wedding:locations-get
    container_name: microservice_locations_get
    env_file: .env
    depends_on:
      - mongo
    ports:
      - "4002:4002"
    networks:
      - pl-network

  microservice_locations_create:
    image: keylet30/province-locations-wedding:locations-create
    container_name: microservice_locations_create
    env_file: .env
    depends_on:
      - mongo
    ports:
      - "4001:4001"
    networks:
      - pl-network

  microservice_locations_delete:
    image: keylet30/province-locations-wedding:locations-delete
    container_name: microservice_locations_delete
    env_file: .env
    depends_on:
      - mongo
    ports:
      - "4003:4003"
    networks:
      - pl-network

  frontend:
    image: keylet30/province-locations-wedding:frontend
    container_name: provinces_locations_frontend
    depends_on:
      - microservice_provinces_get
      - microservice_provinces_delete
      - microservice_locations_get
      - microservice_locations_create
      - microservice_locations_delete
    ports:
      - "8080:80"
    networks:
      - pl-network

volumes:
  mongo_data:

networks:
  pl-network:
    driver: bridge
