version: '3.8'

services:
  user-registration-service:
    image: keylet30/users-wedding:user-registration
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3006:3006"
    depends_on:
      - mysql-db
    networks:
      - users_network

  user-login-service:
    image: keylet30/users-wedding:user-login
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3007:3007"
    depends_on:
      - mysql-db
    networks:
      - users_network

  user-update-service:
    image: keylet30/users-wedding:user-update
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3008:3008"
    depends_on:
      - mysql-db
    networks:
      - users_network

  user-delete-service:
    image: keylet30/users-wedding:user-delete
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3009:3009"
    depends_on:
      - mysql-db
    networks:
      - users_network

  user-get-service:
    image: keylet30/users-wedding:user-get
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3010:3010"
    depends_on:
      - mysql-db
    networks:
      - users_network

  mysql-db:
    image: keylet30/users-wedding:mysql-8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - users_network

  phpmyadmin:
    image: keylet30/users-wedding:phpmyadmin-latest
    environment:
      PMA_HOST: mysql-db
    ports:
      - "8081:80"
    networks:
      - users_network

networks:
  users_network:

volumes:
  mysql-data:
