version: '3'
services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - users_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-db
    ports:
      - "8081:80"
    networks:
      - users_network

  user-registration-service:
    image: users-user-registration-service
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3006:3006"
    depends_on:
      - mysql-db
    networks:
      - users_network

  update-user-service:
    image: users-update-user-service
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3003:3003"
    depends_on:
      - mysql-db
    networks:
      - users_network

  delete-user-service:
    image: users-delete-user-service
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3002:3002"
    depends_on:
      - mysql-db
    networks:
      - users_network

  login-service:
    image: users-login-service
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3004:3004"
    depends_on:
      - mysql-db
    networks:
      - users_network

  get-user-service:
    image: users-get-user-service
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3001:3001"
    depends_on:
      - mysql-db
    networks:
      - users_network

networks:
  users_network:
    driver: bridge

volumes:
  mysql_data:
