# .github/workflows/provinces-locations-deploy.yml
name: provinces-locations-deploy

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions code
        uses: actions/checkout@v3

      - name: Set up SSH for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROVINCES_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.PROVINCES_HOST }}" >> ~/.ssh/known_hosts

      - name: Build & push images
        working-directory: Provinces-Locations
        run: |
          docker compose build
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker compose push

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_rsa "${{ secrets.EC2_USER }}@${{ secrets.PROVINCES_HOST }}" << 'EOF'
            set -e
            cd ~/Provinces-Locations      # Ya debe existir y estar apuntando al repo
            git fetch origin qa
            git checkout qa
            git reset --hard origin/qa

            # Actualiza imágenes y levanta containers
            sudo docker compose pull
            sudo docker compose up -d
          EOF
