name: CI/CD Deployment for Update User Service

on:
  push:
    branches:
      - qa
    paths:
      - 'Users/update-user-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./Users/update-user-service

    - name: Build and push Docker image for update-user-service
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/update-user-service:latest ./Users/update-user-service
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/update-user-service:latest

    - name: Deploy update-user-service to EC2 with Docker Compose
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST_USERS }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY_M }}
        port: 22
        script: |
          if ! command -v docker &> /dev/null; then
            sudo apt-get update -y
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi
          cat > docker-compose.yml <<EOF
          version: '3.8'
          services:
            update-user-service:
              image: ${{ secrets.DOCKER_HUB_USERNAME }}/update-user-service:latest
              ports:
                - "3004:3004"
          EOF
          sudo docker-compose down || true
          sudo docker-compose up -d
