name: Deploy Users Services

on:
  push:
    branches: [ qa ]

env:
  DOCKERHUB_REPO: keylet30/users-wedding

jobs:
  build-and-push:
    name: Build & Push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push user-registration-service
        uses: docker/build-push-action@v4
        with:
          context: ./Users/user-registration-service
          file:    ./Users/user-registration-service/Dockerfile
          push:    true
          tags:    ${{ env.DOCKERHUB_REPO }}:user-registration

      - name: Build & push login-service
        uses: docker/build-push-action@v4
        with:
          context: ./Users/login-service
          file:    ./Users/login-service/Dockerfile
          push:    true
          tags:    ${{ env.DOCKERHUB_REPO }}:user-login

      - name: Build & push update-user-service
        uses: docker/build-push-action@v4
        with:
          context: ./Users/update-user-service
          file:    ./Users/update-user-service/Dockerfile
          push:    true
          tags:    ${{ env.DOCKERHUB_REPO }}:user-update

      - name: Build & push delete-user-service
        uses: docker/build-push-action@v4
        with:
          context: ./Users/delete-user-service
          file:    ./Users/delete-user-service/Dockerfile
          push:    true
          tags:    ${{ env.DOCKERHUB_REPO }}:user-delete

      - name: Build & push get-user-service
        uses: docker/build-push-action@v4
        with:
          context: ./Users/get-user-service
          file:    ./Users/get-user-service/Dockerfile
          push:    true
          tags:    ${{ env.DOCKERHUB_REPO }}:user-get

      - name: Build & push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./Users/frontend
          file:    ./Users/frontend/Dockerfile
          push:    true
          tags:    ${{ env.DOCKERHUB_REPO }}:frontend
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host:             ${{ secrets.EC2_HOST }}
          username:         ${{ secrets.EC2_USER }}
          key:              ${{ secrets.EC2_SSH_KEY }}
          port:             22
          timeout:
